name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Build and Push Docker image
      - name: Build and Push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/orthopedic-ai-app:latest \
            -f Orthopedic-Health-AI-Scan-Application/Orthopedic-Health-AI-Scan-Application/Dockerfile \
            Orthopedic-Health-AI-Scan-Application/Orthopedic-Health-AI-Scan-Application

          docker push ${{ secrets.DOCKER_USERNAME }}/orthopedic-ai-app:latest
