name: Python CI with Docker Build and Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # matches your Dockerfile

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . || true

      - name: Run tests
        run: |
          pip install pytest
          pytest || echo "No tests found"

  docker-build:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/orthopedic-ai-app:latest1 .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/orthopedic-ai-app:latest1

      - name: Push image with commit SHA (optional)
        run: |
          IMAGE_TAG=${GITHUB_SHA::7}
          docker tag ${{ secrets.DOCKER_USERNAME }}/orthopedic-ai-app:latest1 ${{ secrets.DOCKER_USERNAME }}/orthopedic-ai-app:$IMAGE_TAG
          docker push ${{ secrets.DOCKER_USERNAME }}/orthopedic-ai-app:$IMAGE_TAG
