name: Python CI with Docker Build and Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . || true

      - name: Run tests
        run: |
          pip install pytest
          pytest || echo "No tests found"

  docker-build:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          # 👇 Changed build context path (was '.' earlier)
          # Your Dockerfile lives inside:
          # Orthopedic-Health-AI-Scan-Application/Orthopedic-Health-AI-Scan-Application
          docker build -t ${{ secrets.DOCKER_USERNAME }}/orthopedic-ai-app:latest ./Orthopedic-Health-AI-Scan-Application/Orthopedic-Health-AI-Scan-Application

  docker-push:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          # 👇 This step is unchanged
          docker push ${{ secrets.DOCKER_USERNAME }}/orthopedic-ai-app:latest

      - name: Push image with commit SHA
        run: |
          # 👇 This step is unchanged too
          IMAGE_TAG=${GITHUB_SHA::7}
          docker tag ${{ secrets.DOCKER_USERNAME }}/orthopedic-ai-app:latest ${{ secrets.DOCKER_USERNAME }}/orthopedic-ai-app:$IMAGE_TAG
          docker push ${{ secrets.DOCKER_USERNAME }}/orthopedic-ai-app:$IMAGE_TAG
