name: Docker CI/CD Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Login to Docker Hub (⚠️ hardcoded for testing only)
      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: "srdeveloper9081"
          password: "dckr_pat_51pIMyf2osURhhp-CiOKMp-A3Io"

      # 3️⃣ Build Docker image
      - name: Build Docker image
        run: docker build -t srdeveloper9081/orthopedic-health-ai:latest .

      # 4️⃣ Push Docker image
      - name: Push Docker image
        run: docker push srdeveloper9081/orthopedic-health-ai:latest
