name: Docker CI/CD Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Login to Docker Hub
      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: "srdeveloper9081"
          password: "dckr_pat_51pIMyf2osURhhp-CiOKMp-A3Io"

      # 3️⃣ SonarCloud Scan
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=Salil9081_Orthopedic-Health-AI-Scan-Application
            -Dsonar.organization=salil9081
            -Dsonar.python.version=3.11
            -Dsonar.sources=.

      # 4️⃣ Build Docker image
      - name: Build Docker image
        run: docker build -t srdeveloper9081/orthopedic-health-ai:latest .

      # 5️⃣ Trivy scan Docker image
      - name: Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'srdeveloper9081/orthopedic-health-ai:latest'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'

      # 6️⃣ Push Docker image
      - name: Push Docker image
        run: docker push srdeveloper9081/orthopedic-health-ai:latest

