name: Docker CI/CD Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Log in to Docker Hub
      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}   # must match your Docker Hub username
          password: ${{ secrets.DOCKER_PASSWORD }}   # must be your Docker Hub PAT (not account password)

      # 3️⃣ Build Docker image
      - name: Build Docker image
        run: |
          docker build \
            -t srdeveloper9081/orthopedic-ai-app:latest \
            -f Dockerfile .

      # 4️⃣ Push Docker image (latest)
      - name: Push Docker image (latest)
        run: |
          docker push srdeveloper9081/orthopedic-ai-app:latest

      # 5️⃣ Push Docker image with commit SHA tag
      - name: Push Docker image (commit SHA)
        run: |
          IMAGE_TAG=${GITHUB_SHA::7}
          docker tag srdeveloper9081/orthopedic-ai-app:latest srdeveloper9081/orthopedic-ai-app:$IMAGE_TAG
          docker push srdeveloper9081/orthopedic-ai-app:$IMAGE_TAG

         
