name: Python CI/CD with Docker, Trivy, and SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    env:
      # SonarCloud token from GitHub Secrets
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      # Docker Hub credentials from GitHub Secrets
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      IMAGE_NAME: salil9081/orthopedic-health-ai-scan-app

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Set up Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4️⃣ Run SonarCloud Scan
      - name: SonarCloud Scan
        run: |
          ${GITHUB_ACTION_PATH}/scripts/run-sonar-scanner-cli.sh \
            -Dsonar.projectKey=Salil9081_Orthopedic-Health-AI-Scan-Application \
            -Dsonar.organization=salil9081 \
            -Dsonar.python.version=3.11 \
            -Dsonar.sources=. \
            -Dsonar.login=$SONAR_TOKEN

      # 5️⃣ Log in to Docker Hub
      - name: Docker Login
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      # 6️⃣ Build Docker image
      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:latest .

      # 7️⃣ Scan Docker image with Trivy
      - name: Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: $IMAGE_NAME:latest
          format: 'table'
          exit-code: '1'
          severity: 'HIGH,CRITICAL'

      # 8️⃣ Push Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME:latest

