name: Docker Build and Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          logout: true  # optional

      # 3️⃣ Build Docker image (from root folder)
      - name: Build Docker image
        run: |
          set -e
          docker build --progress=plain \
            -t srdeveloper9081/orthopedic-ai-app:latest \
            -f Dockerfile \
            .

      # 4️⃣ Push Docker image (latest tag)
      - name: Push Docker image (latest)
        run: |
          set -e
          docker push srdeveloper9081/orthopedic-ai-app:latest

      # 5️⃣ Push Docker image with commit SHA tag
      - name: Push Docker image (commit SHA)
        run: |
          set -e
          IMAGE_TAG=${GITHUB_SHA::7}
          docker tag srdeveloper9081/orthopedic-ai-app:latest srdeveloper9081/orthopedic-ai-app:$IMAGE_TAG
          docker push srdeveloper9081/orthopedic-ai-app:$IMAGE_TAG
